config/routes.rb
Rails.application.routes.draw do
  root 'welcome#show'

  get '/auth/twitter', as: :login

  get '/auth/twitter/callback', to: 'sessions#create'

  get '/logout', as: :logout, to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#show'

  resources :users, only: [:show]

  put '/resolutions/:id/complete', as: :complete, to: 'resolutions#complete'
  put '/resolutions/:id/again', as: :again, to: 'resolutions#again'

  resources :resolutions, except: [:index] do
    resources :reminders, except: [:index]
    resources :tweets, only: [:create]
    put '/goals/:id/goal_complete', as: :goal_complete, to: 'goals#goal_complete'
    resources :goals, except: [:index]
  end

  post 'notifications/notify', to: 'notifications#notify'
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates_presence_of :name

  belongs_to :resolution

  def self.completed_goals
    where(completed: true)
  end

  def self.current_goals
    where(completed: false)
  end
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  validates :phone_number, presence: true

  belongs_to :resolution

  after_create :remind

  def remind
    TwilioService.twilio_client(resolution, recipient, self.phone_number)
  end

  private

  def resolution
    @resolution ||= Resolution.find_by(id: resolution_id)
  end

  def recipient
    User.find(resolution[:user_id])
  end
end

app/models/resolution.rb
class Resolution < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 115 }

  has_many :goals, dependent: :destroy
  has_many :reminders, dependent: :destroy
  belongs_to :user

  FORGOTTEN_THRESHOLD = 30.days.ago
  def self.completed
    where(finished: true)
  end

  def self.current
    where(finished: false)
  end

  def self.forgotten
    empty_old_resolutions | resolutions_with_only_inactive_goals
  end

  # Return only resolutions that haven't been changed in over 30 days (created_at) AND have no goals
  def self.empty_old_resolutions
    resolutions_with_no_goals - ("updated_at < '#{FORGOTTEN_THRESHOLD}'")
  end

  def self.resolutions_with_no_goals
    joins(:goals).where(goals: {id: nil})
  end

  def self.resolutions_with_only_inactive_goals
    self
      .joins(:goals)
      .where("goals.updated_at < '#{FORGOTTEN_THRESHOLD}'")
  end

  def completed_goals
    goals.completed_goals
  end

  def current_goals
    goals.current_goals
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :resolutions

  def self.from_omniauth(auth_info)
    user = find_or_create_by(uid: auth_info.uid)
    user.update_attributes(name:               auth_info.extra.raw_info.name,
                           profile_image:      auth_info.info.image,
                           oath_token:         auth_info.credentials.token,
                           oauth_token_secret: auth_info.credentials.secret
                           )

    user
  end

  def twitter
    TwitterService.twitter_client(oath_token, oauth_token_secret)
  end

  def inspirational_tweets
    twitter.search("#motivation -rt").first(10)
  end

  def current_resolutions
    resolutions.current.reverse
  end

  def completed_resolutions
    resolutions.completed.reverse
  end

  def forgotten_resolutions
    resolutions.forgotten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @resolutions = current_user.current_resolutions
    @forgotten = current_user.forgotten_resolutions
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @resolution = Resolution.find(params[:resolution_id])
    @goal = Goal.new
  end

  def create
    goal = resolution.goals.where(goal_params).first_or_create
    if goal.save
      flash[:notice] = "Goal created for #{resolution.title}"
      redirect_to dashboard_path
    else
      flash[:notice] = "Please try again"
      redirect_to dashboard_path
    end
  end

  def edit
    @resolution = Resolution.find(params[:resolution_id])
    @goal = Goal.find(params[:id])
  end

  def update
    goal = Goal.find(params[:id])
    if goal.update(goal_params)
      flash[:notice] = "Goal Updated Successfully"
      redirect_to dashboard_path
    else
      flash[:notice] = "Please try again"
      redirect_to dashboard_path
    end
  end

  def destroy
    resolution.goals.find(params[:id]).destroy
    flash[:notice] = "Goal removed"
    redirect_to dashboard_path
  end

  def goal_complete
    goal = resolution.goals.find(params[:id])
    goal.update(completed: true)
    flash[:notice] = "Congratulations on reaching your goal!"
    redirect_to dashboard_path
  end

  private

  def resolution
    @resolution ||= Resolution.find(params[:resolution_id])
  end

  def goal_params
    params.require(:goal).permit(:resolution_id, :name, :completed)
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def new
    @resolution = Resolution.find(params[:resolution_id])
    @reminder = Reminder.new
  end

  def create
    resolution = Resolution.find(params[:resolution_id])
    resolution.reminders.where(reminder_params).first_or_create
    flash[:notice] = "Reminder created for #{resolution.title}"
    redirect_to dashboard_path
  end

  def destroy
    resolution.reminder.find(params[:id]).destroy
    flash[:notice] = "Reminder removed"
    redirect_to dashboard_path
  end

  private

  def reminder_params
    params.require(:reminder).permit(:phone_number)
  end
end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  def show
  end

  def index
  end

  def new
    @resolution = Resolution.new
  end

  def create
    @resolution = current_user.resolutions.where(resolution_params).first_or_create
    if current_user && @resolution.save
      flash[:notice] = "Resolution created!"
      redirect_to dashboard_path
    else
      flash.now[:notice] = "Please try again"
      render :new
    end
  end

  def edit
    @resolution = Resolution.find(params[:id])
  end

  def update
    @resolution = Resolution.find(params[:id])
    if @resolution.update(resolution_params)
      flash[:notice] = "Resolution Updated Successfully"
      redirect_to dashboard_path
    else
      flash.now[:notice] = "Please try again"
      render :edit
    end
  end

  def destroy
    resolution = Resolution.find(params[:id])
    resolution.destroy
    redirect_to dashboard_path
  end

  def complete
    resolution = Resolution.find(params[:id])
    resolution.update(finished: true)
    flash[:notice] = "Congratulations, your resolution is complete!"
    redirect_to user_path(current_user)
  end

  def again
    resolution = Resolution.find(params[:id])
    resolution.update(finished: false)
    flash[:notice] = "Your resolution is now active again"
    redirect_to dashboard_path
  end

  private

  def resolution_params
    params.require(:resolution).permit(:user_id, :title, :description, :motive_image, :finished)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(oauth_data)
    if user
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def oauth_data
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    tweet_body = "My new resolution is: #{resolution.title}!"
    send_tweet(tweet_body)
    redirect_to dashboard_path, flash: { notice: "Tweeted successfully!" }
  end

  private

  def resolution
    @resolution ||= Resolution.find(params[:resolution_id])
  end

  def send_tweet(tweet_body)
    current_user.twitter.update(tweet_body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/resolutions_helper.rb
module ResolutionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/show.html.erb
<%= render "partials/topbar" %>

<section class="hero-dashboard">
  <div class="row">
    <div class="large-6 large-push-2 columns">
      <div class="circle-bg quote-1">
        <p>Change your life.<br> You can do it.</p>
      </div>
    </div>
    <div class="large-6 large-pull-2 columns">
      <div class="circle-bg quote-2">
        <p>The journey of a thousand miles is made up of many small steps.</p>
      </div>
    </div>
  </div>
</section>

<div class="row">
  <div class="large-8 columns">
    <h4><div class="dash4">Resolutions</div></h4>
    <% unless @forgotten.empty? %>
      <div class="forgotten">The following Resolutions have no changes for the past 30 days!:
      <% @forgotten.each do |resolution| %>
        <li><%= resolution.title %></li>
      <% end %>
      </div>
    <% end %>
    <br>
    <% @resolutions.each do |resolution| %>
      <div class="row">
        <div class="large-12 columns">
          <div class="card">
            <div class="content">
              <span><a href="#" data-reveal-id="myModal"> <%= resolution.title %></a></span>

              <div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
                <p class="lead">Goals for <%= resolution.title %></p>
                <% resolution.current_goals.each do |goal| %>
                  <h5><%= link_to goal.name, edit_resolution_goal_path(resolution, goal) %>
                    <%= link_to "Goal met", resolution_goal_complete_path(resolution, goal), method: :put, class: "tiny round button" %>
                    <%= link_to "Delete", resolution_goal_path(resolution, goal), method: :delete, class: "tiny round button alert" %></h5>
                <% end %>
                <h5> Completed Goals </h5>
                <% resolution.completed_goals.each do |goal| %>
                  <h5><%= goal.name %></h5>
                <% end %>
                <a class="close-reveal-modal" aria-label="Close">&#215;</a>
              </div>

              <p><%= resolution.description %></p>
            </div>
            <div class="action">
              <%= link_to "Edit", edit_resolution_path(resolution), class: "link" %>
              <%= link_to "Delete", resolution_path(resolution), method: :delete, data: {confirm: "This will remove your resolution. Are you sure?"}, class: "link" %>
              <%= link_to "Add Goal", new_resolution_goal_path(resolution), class: "link" %>
              <%= link_to "Tweet This", resolution_tweets_path(resolution), method: :post, class: "link" %>
              <%= link_to "Reminder", new_resolution_reminder_path(resolution), class: "link" %>
              <%= link_to "Mark Complete!", complete_path(resolution), method: :put, class: "link" %>
            </div>
          </div>
        </div>
      </div>
      <br>
    <% end %>
  </div>

  <aside class="large-4 columns hide-for-small">
    <h4><div class="dash4">Motivation</div></h4>
    <br>
    <ol>
      <% cache do %>
        <% current_user.inspirational_tweets.each do |tweet| %>
          <li><%= tweet.text %></li>
          <br>
        <% end %>
      <% end %>
    </ol>
  </aside>

</div>

<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-5 columns">
        <p>&copy; Copyright Creative License, 2015</p>
      </div>
    </div>
  </div>
</footer>

app/views/goals/edit.html.erb
<%= render "partials/topbar_new" %>
<%= render "partials/goal_form" %>

app/views/goals/new.html.erb
<%= render "partials/topbar_new" %>
<%= render "partials/goal_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= render 'partials/messages' %>
<%= yield %>

</body>
</html>

app/views/partials/_form.html.erb
<section class="hero-dashboard">
  <div class="row">
    <div class="large-6 large-push-2 columns">
      <div class="circle-bg quote-1">
        <p>What are you doing?</p>
      </div>
    </div>
    <div class="large-6 large-pull-2 columns">
      <div class="circle-bg quote-2">
        <p>And WHY are you doing it?</p>
      </div>
    </div>
  </div>
</section>

<div class="large-6 large-centered columns">
  <div class="card">
    <div class="content">
      <div class="form-card">
        <%= form_for(@resolution, multiplart: true) do |f| %>
          <label for="resolution_title">Resolution</label>
          <%= f.text_field :title %>
          <label for="resolution_description">Reasons - Why are you doing it?</label>
          <%= f.text_area :description %>
          <br>
          <% if @resolution.id %>
            <%= f.submit "Edit", class: "button round small", method: :put %>
          <%else %>
            <%= f.submit "Create", class: "button round medium" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_goal_form.html.erb
<section class="hero-dashboard">
  <div class="row">
    <div class="large-6 large-push-2 columns">
      <div class="circle-bg quote-1">
        <p>Make a goal.</p>
      </div>
    </div>
    <div class="large-6 large-pull-2 columns">
      <div class="circle-bg quote-2">
        <p>Then go after it.</p>
      </div>
    </div>
  </div>
</section>

<div class="large-6 large-centered columns">
  <div class="card">
    <div class="content">
      <div class="form-card">
        <%= form_for([@resolution, @goal]) do |f| %>
          <label for="goal_name">What is the goal you will use to fulfill your resolution</label>
          <%= f.text_field :name %>
          <br>
          <% if @goal.id %>
            <%= f.submit "Edit", class: "button round small", method: :put %>
          <% else %>
            <%= f.submit "Create", class: "button round medium" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_messages.html.erb
<link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
<% flash.each do |name, msg| %>
  <div class="row">
    <div class="small-6 columns small-centered">
      <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
        <i class="fi-eye"></i><%= msg %>
        <a href="#" class="close">&CircleTimes;</a>
      </div>
    </div>
  </div>
<% end %>

app/views/partials/_reminder_form.erb
<section class="hero-dashboard">
  <div class="row">
    <div class="large-6 large-push-2 columns">
      <div class="circle-bg quote-1">
        <p>Remind yourself what.</p>
      </div>
    </div>
    <div class="large-6 large-pull-2 columns">
      <div class="circle-bg quote-2">
        <p>Think about why.</p>
      </div>
    </div>
  </div>
</section>

<div class="large-6 large-centered columns">
  <div class="card">
    <div class="content">
      <div class="form-card">
        <%= form_for([@resolution, @reminder]) do |f| %>
          <label for="phone">Your phone number</label>
          <%= f.text_field :phone_number %>
          <br>
          <%= f.submit "Create Reminder", class: "button round medium" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_topbar.html.erb
<div class="fixed">
<nav class="top-bar" data-topbar role="navigation" data-options="sticky_on">
  <section class="top-bar-section">
    <ul class="buttons-topbar">
      <li><%= link_to "Logout", logout_path %></li>
      <li><%= link_to "Profile", user_path(current_user) %></li>
      <li><%= link_to "Create a Resolution", new_resolution_path %></li>
    </ul>
  </section>
</nav>
</div>

app/views/partials/_topbar_new.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on">
    <section class="top-bar-section">
      <ul class="buttons-topbar">
        <li><%= link_to "Logout", logout_path %></li>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Home", dashboard_path %></li>
      </ul>
    </section>
  </nav>
</div>

app/views/partials/_topbar_profile.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on">
    <section class="top-bar-section">
      <ul class="buttons-topbar">
        <li><%= link_to "Logout", logout_path %></li>
        <li><%= link_to "Create a Resolution", new_resolution_path %></li>
        <li><%= link_to "Home", dashboard_path %></li>
      </ul>
    </section>
  </nav>
</div>

app/views/reminders/new.html.erb
<%= render "partials/topbar_new" %>
<%= render "partials/reminder_form" %>

app/views/resolutions/edit.html.erb
<%= render "partials/topbar_new" %>
<%= render "partials/form" %>

app/views/resolutions/new.html.erb
<%= render "partials/topbar_new" %>
<%= render "partials/form" %>

app/views/users/show.html.erb
<%= render "partials/topbar_profile" %>

<section class="hero-profile">
</section>

<div class="row">
  <div class="large-12 columns">
    <h4><div class="dash4">Hello, <%= current_user.name %>. Here are your Victories.</div></h4>
    <br>
  </div>
</div>
<% current_user.completed_resolutions.each do |resolution| %>
  <div class="row">
    <div class="large-12 columns">
      <div class="card">
        <div class="content">
          <span><a href="#" data-reveal-id="myModal"> <%= resolution.title %></a></span>

          <div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
            <p class="lead">Goals completed for <%= resolution.title %></p>
            <% resolution.goals.each do |goal| %>
              <h5><%= goal.name %></h5>
            <% end %>
            <a class="close-reveal-modal" aria-label="Close">&#215;</a>
          </div>
          <p><%= resolution.description %></p>
        </div>
        <div class="action">
          <%= link_to "Do this again!", again_path(resolution), method: :put %>
        </div>
      </div>
    </div>
  </div>
  <br>
<% end %>

app/views/welcome/show.html.erb
<header class="hero">
  <h1>
    <div class="title">Resolutionary</div>
    <div class="title-small">The app that will change your life</div>
    <div class="row">
      <div class="small-12 columns">
        <%= link_to login_path do %>
          <%= content_tag :span, "sign in with twitter", class: "twitter round button" %>
          <% end %>
      </div>
    </div>
  </h1>
</header>
<footer class="footer">
  <div class="row">
    <div class="small-12 columns">
      <p class="copywrite">Copywrite Creative License © 2015</p>
    </div>
  </div>
</footer>